default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['db.username'] %>
  password: <%= ENV['db.password'] %>
  host:  <%= ENV['db.host'] %>

development:
  <<: *default
  database: tailwind_skeleton_development

test:
  <<: *default
  browser.headless: 'true'
  database: tailwind_skeleton_test

production:
  <<: *default
  database: tailwind_skeleton_production