default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['db.username'] %>
  password: <%= ENV['db.password'] %>
  host:  <%= ENV['db.host'] %>

mailer: &mailer
  mailer.host: localhost
  mailer.port: '3000'

development:
  <<: *default
  <<: *mailer
  database: tailwind_skeleton_development

test:
  <<: *default
  <<: *mailer
  browser.headless: 'true'
  database: tailwind_skeleton_test

production:
  <<: *default
  database: tailwind_skeleton_production